services:
  auth-db:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: ${DB_AUTH_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_PASSWD}
      POSTGRES_DB: ${DB_AUTH_NAME}

    volumes:
      - auth-db-data:/var/lib/postgresql/data/

    networks:
      - auth-net

    restart: unless-stopped

  auth-service:
    build:
      context: ${AUTH_SERVICE_DIR}
      dockerfile: Dockerfile

    env_file:
      - ./Services/AuthService/.env

    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: ${DB_AUTH_NAME}
      DB_USER: ${DB_AUTH_USER}
      DB_PASSWD: ${DB_AUTH_PASSWD}

      JWT_ALGORITHM: ${JWT_ALGORITHM}
      PRIVATE_KEY_PATH: ${JWT_PRIVATE_KEY_CONTAINER_PATH}
      PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_CONTAINER_PATH}

    volumes:
      - ${JWT_PRIVATE_KEY_HOST_PATH}:${JWT_PRIVATE_KEY_CONTAINER_PATH}:ro
      - ${JWT_PUBLIC_KEY_HOST_PATH}:${JWT_PUBLIC_KEY_CONTAINER_PATH}:ro

    depends_on:
      - auth-db

    networks:
      - auth-net
      - service-mesh-net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=service-mesh-net"

      - "traefik.http.routers.auth.rule=Host(`app.docker.localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"

      - "traefik.http.services.auth.loadbalancer.server.port=8000"

      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth.middlewares=auth-strip"

    restart: unless-stopped

  federation-db:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: ${DB_FEDERATION_USER}
      POSTGRES_PASSWORD: ${DB_FEDERATION_PASSWD}
      POSTGRES_DB: ${DB_FEDERATION_NAME}

    volumes:
      - federation-db-data:/var/lib/postgresql/data/

    networks:
      - federation-net

    restart: unless-stopped

  federation-service:
    build:
      context: ${FEDERATION_SERVICE_DIR}
      dockerfile: Dockerfile

    env_file:
      - ./Services/FedService/.env

    environment:
      DB_HOST: federation-db
      DB_PORT: 5432
      DB_NAME: ${DB_FEDERATION_NAME}
      DB_USER: ${DB_FEDERATION_USER}
      DB_PASSWD: ${DB_FEDERATION_PASSWD}

      AUTH_HOST: auth-service
      AUTH_PORT: 8000

      JWT_ALGORITHM: ${JWT_ALGORITHM}
      PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_CONTAINER_PATH}

    volumes:
      - ${JWT_PUBLIC_KEY_HOST_PATH}:${JWT_PUBLIC_KEY_CONTAINER_PATH}:ro

    depends_on:
      - federation-db
      - auth-service

    networks:
      - federation-net
      - service-mesh-net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=service-mesh-net"

      - "traefik.http.routers.federation.rule=Host(`app.docker.localhost`) && PathPrefix(`/federation`)"
      - "traefik.http.routers.federation.entrypoints=websecure"
      - "traefik.http.routers.federation.tls=true"

      - "traefik.http.services.federation.loadbalancer.server.port=8000"

      - "traefik.http.middlewares.federation-strip.stripprefix.prefixes=/federation"
      - "traefik.http.routers.federation.middlewares=federation-strip"

    restart: unless-stopped

volumes:
  auth-db-data:
  federation-db-data:

networks:
  auth-net:
    driver: bridge

  federation-net:
    driver: bridge

  service-mesh-net:
    external: true
    name: service-mesh-net
