services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - service-mesh-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=service-mesh-net"

      - "traefik.http.routers.frontend.rule=Host(`app.docker.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.priority=1"

      - "traefik.http.services.frontend.loadbalancer.server.port=4200"
    restart: unless-stopped

networks:
  service-mesh-net:
    external: true
    name: service-mesh-net
