#!/usr/bin/env bash
set -euo pipefail

COMMAND="${1:-start}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/Services/.env"

TRAEFIK_COMPOSE="$ROOT_DIR/Config/docker-compose.traefik.yml"
PORTAINER_COMPOSE="$ROOT_DIR/Config/docker-compose.portainer.yml"
SERVICES_COMPOSE="$ROOT_DIR/Services/docker-compose.yml"

if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: missing env file: $ENV_FILE"
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

CERTS_DIR="$ROOT_DIR/Config/certs"
DYNAMIC_DIR="$ROOT_DIR/Config/dynamic"
JWT_KEYS_DIR_ABS="$ROOT_DIR/${JWT_KEYS_DIR#./}"
JWT_PRIVATE_KEY_ABS="$ROOT_DIR/${JWT_PRIVATE_KEY_HOST_PATH#./}"
JWT_PUBLIC_KEY_ABS="$ROOT_DIR/${JWT_PUBLIC_KEY_HOST_PATH#./}"

compose_cmd() {
  docker compose \
    --project-directory "$ROOT_DIR" \
    --env-file "$ENV_FILE" \
    -f "$TRAEFIK_COMPOSE" \
    -f "$PORTAINER_COMPOSE" \
    -f "$SERVICES_COMPOSE" \
    "$@"
}

setup() {
  mkdir -p "$CERTS_DIR" "$DYNAMIC_DIR" "$JWT_KEYS_DIR_ABS"

  if [ ! -f "$CERTS_DIR/local.key" ] || [ ! -f "$CERTS_DIR/local.crt" ]; then
    echo "Generating local Traefik TLS certificate..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout "$CERTS_DIR/local.key" \
      -out "$CERTS_DIR/local.crt" \
      -subj "/CN=*.docker.localhost" \
      -addext "subjectAltName=DNS:*.docker.localhost,DNS:docker.localhost,DNS:localhost,IP:127.0.0.1"
  else
    echo "Traefik TLS certificate already exists."
  fi

  cat > "$DYNAMIC_DIR/tls.yaml" <<TLS
# Generated by deploy.sh
tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key
TLS

  if [ ! -f "$JWT_PRIVATE_KEY_ABS" ] || [ ! -f "$JWT_PUBLIC_KEY_ABS" ]; then
    echo "Generating JWT RSA key pair..."
    echo "  algorithm: $JWT_ALGORITHM"
    echo "  key size:  $JWT_KEY_SIZE"

    openssl genpkey \
      -algorithm RSA \
      -out "$JWT_PRIVATE_KEY_ABS" \
      -pkeyopt rsa_keygen_bits:"$JWT_KEY_SIZE"

    openssl rsa \
      -pubout \
      -in "$JWT_PRIVATE_KEY_ABS" \
      -out "$JWT_PUBLIC_KEY_ABS"

    chmod 0400 "$JWT_PRIVATE_KEY_ABS"
    chmod 0444 "$JWT_PUBLIC_KEY_ABS"
  else
    echo "JWT key pair already exists."
  fi

  if ! docker network inspect service-mesh-net >/dev/null 2>&1; then
    echo "Creating shared Docker bridge network: service-mesh-net"
    docker network create service-mesh-net
  else
    echo "Docker network already exists: service-mesh-net"
  fi

  echo "Setup completed."
}

start() {
  setup

  cd "$ROOT_DIR"

  compose_cmd up -d --build

  echo
  echo "Deployment completed."
  echo
  echo "Local URLs:"
  echo "  Traefik dashboard: https://dashboard.docker.localhost/dashboard/"
  echo "  Whoami:            https://whoami.docker.localhost"
  echo "  Portainer:         https://portainer.docker.localhost"
  echo "  Auth service:      https://app.docker.localhost/api/v1/auth"
  echo "  Federation:        https://app.docker.localhost/api/v1/fed"
  echo
  echo "If DNS does not resolve, add these lines to /etc/hosts:"
  echo "  127.0.0.1 dashboard.docker.localhost"
  echo "  127.0.0.1 whoami.docker.localhost"
  echo "  127.0.0.1 portainer.docker.localhost"
  echo "  127.0.0.1 app.docker.localhost"
}

down() {
  cd "$ROOT_DIR"

  docker stop $(docker ps -q)

  echo "Containers stopped."
  echo "Volumes were preserved."
}

remove() {
  cd "$ROOT_DIR"
  docker rm $(docker ps -qa)
  docker volume rm $(docker volume ls -q)

  echo "Containers removed."
  echo "Volumes were not preserved."
}

usage() {
  echo "Usage:"
  echo "  ./deploy.sh setup   Generate certs, tls.yaml, JWT keys, and Docker network"
  echo "  ./deploy.sh start   Run setup, then start all containers"
  echo "  ./deploy.sh down    Stop all Compose Containers. Preserve Volumes"
  echo "  ./deploy.sh remove  Remove all Compose Containers and Volumes"
}

case "$COMMAND" in
  setup)
    setup
    ;;
  start)
    start
    ;;
  down)
    down
    ;;
  remove)
    remove
    ;;
  *)
    usage
    exit 1
    ;;
esac