Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  vms = {
    "vm1" => "192.168.56.11",
    "vm2" => "192.168.56.12",
    "vm3" => "192.168.56.13",
    # "vm4" => "192.168.56.14"
  }

  vms.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
      end

      node.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update -y
        
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin python3-docker
        
        usermod -aG docker vagrant
      SHELL
    end
  end
end