---
primaryManager: "{{ groups['swarmManagers'][0] }}"
primaryManagerIp: "{{ hostvars[primaryManager].swarmIp }}"

swarmRegistryPort: 5000
swarmRegistryAddr: "{{ primaryManagerIp }}:{{ swarmRegistryPort }}"

remoteServicesRoot: /opt/swarm-services
remoteStacksRoot: /opt/swarm-stacks

sharedOverlayNetwork: shared-service-net

localServiceRoot: /home/filippo/Documents/uni/uni-sw-arch/Backend/Services

secretsRoot: /opt/swarm-secrets

jwtPrivateKeyPath: "{{ secretsRoot }}/jwt_private.pem"
jwtPublicKeyPath: "{{ secretsRoot }}/jwt_public.pem"

jwtPrivateKeySecretName: jwtPrivateKey
jwtPublicKeySecretName: jwtPublicKey
jwtKeySize: 4096

authDbPasswordSecretName: authDbPassword
authDbPasswordSecretPath: "{{ secretsRoot }}/auth_db_password.txt"

authDbName: auth_db
authDbUser: auth_user

authInternalPort: 8000
authReplicas: 2

traefikStackName: traefik
traefikStackPath: "{{ remoteStacksRoot }}/traefik/docker-compose.yml"
traefikImage: traefik
traefikNetwork: "{{ sharedOverlayNetwork }}"
traefikHttpPort: 80
traefikHttpsPort: 443
traefikDashboardPort: 8080

portainerStackName: portainer
portainerHttpPort: 9000
portainerHttpsPort: 9443
portainerPathPrefix: /portainer
portainerInternalPort: 9000

rabbitmqConfigName: rabbitmqConfig
rabbitmqConfigPath: "{{ remoteStacksRoot }}/rabbitmq/rabbitmq.conf"

rabbitmqStackName: rabbitmq
rabbitmqStackPath: "{{ remoteStacksRoot }}/rabbitmq/docker-compose.yml"
rabbitmqImage: rabbitmq:4-management
rabbitmqInternalManagementPort: 15672
rabbitmqManagementPathPrefix: /rabbitmq
rabbitmqDataVolume: rabbitmq-data

rabbitmqUserSecretName: rabbitmqUser
rabbitmqPasswordSecretName: rabbitmqPassword
rabbitmqUserSecretPath: "{{ secretsRoot }}/rabbitmq_user.txt"
rabbitmqPasswordSecretPath: "{{ secretsRoot }}/rabbitmq_password.txt"