---
swarmServices:
  - name: auth
    stackName: auth

    localSrc: "{{ localServiceRoot }}/AuthService"
    remoteSrc: "{{ remoteServicesRoot }}/auth"

    imageName: auth-service-img
    imageTag: latest

    composeTemplate: auth-stack.yml.j2
    composeRemotePath: "{{ remoteStacksRoot }}/auth/docker-compose.yml"

    replicas: "{{ authReplicas }}"
    internalPort: "{{ authInternalPort }}"

    dbName: "{{ authDbName }}"
    dbUser: "{{ authDbUser }}"

    traefik:
      enabled: true
      routerName: auth
      rule: "PathPrefix(`/auth`)"
      entrypoint: web
      stripPrefix: true
      stripPrefixMiddlewareName: auth-strip-prefix