---
vaultAuthDbPassword: "auth_password"

vaultPortainerAdminUser: "admin"
vaultPortainerAdminPassword: "ChangeMeStrongPassword123!"

vaultRabbitmqUser: "rabbitmqUser"
vaultRabbitmqPassword: "ChangeMeRabbitPassword123!"