services:
  auth-db:
    # container_name: auth-db
    image: postgres:15-alpine
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}

    # FOR DEBUGGING
    # ports:
    #   - ${DB_PORT}:5432

    volumes:
      - auth-db-data:/var/lib/postgresql/data/

    networks:
      - auth-net
    
    restart: unless-stopped

  auth-serivce:
    build: .
    restart: unless-stopped

    ports:
      - ${SERVICE_PORT}:8000

    depends_on:
      - auth-db

    networks:
      - auth-net


volumes:
  auth-db-data:

networks:
  auth-net:
    driver: bridge
