services:
  auth-db:
    # container_name: auth-db
    image: postgres:15-alpine
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}

    # FOR DEBUGGING
    # ports:
    #   - ${DB_PORT}:5432

    volumes:
      - auth-db-data:/var/lib/postgresql/data/

    networks:
      - auth-net

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    

  auth-service:
    image: 127.0.0.1:5000/auth-service-img:latest
    build: .

    ports:
      - "${SERVICE_PORT}:8000"

    env_file:
      - ./.env
    
    depends_on:
      - auth-db

    networks:
      - auth-net
      - shared-service-net

    secrets:
      - jwtPrivateKey
      - jwtPublicKey

    deploy:
      replicas: ${REPLICAS}
      restart_policy:
        condition: on-failure


volumes:
  auth-db-data:

networks:
  auth-net:
    driver: overlay
    internal: true
    name: auth-net

  shared-service-net:
    external: true
    name: shared-service-net

secrets:
  jwtPrivateKey:
    external: true
  jwtPublicKey:
    external: true
